### ISSUE TITLE
OSX Chrome No Scrollbar

### ISSUE THREAD

**Issue by icirellik** [icirellik/glowforge-material-manager#20]
Scrollbars in the plugin do not display in all cases on High Sierra, there are several opens bugs surrounding this issue. The solution may be as simple as adding:

```css
.App-grid { overflow: scroll; height: 500px; }
```

to the style sheet.
